[package]
name = "async-timer"
version = "0.5.0"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
description = "Timers for Rust async story"
readme = "README.md"
repository = "https://github.com/DoumanAsh/async-timer"
license = "Apache-2.0"
keywords = ["timer", "async", "wasm"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[features]
default = []
# Requires alloc
no_std = []
# Enables usage of tokio
tokio_on = ["mio", "tokio-reactor", "nix"]

[target.'cfg(any(target_os = "macos", target_os = "ios", unix))'.dependencies]
libc = "0.2.60"
mio = { version = "0.6", optional = true }
tokio-reactor = { version = "0.2.0-alpha", optional = true }

#kqueue needs nix
[target.'cfg(any(target_os = "bitrig", target_os = "dragonfly", target_os = "freebsd", target_os = "ios", target_os = "macos", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
nix = { version = "0.15", optional = true }

[target.'cfg(any(target_arch = "wasm32"))'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["threadpoolapiset"]

[dev-dependencies]
futures-preview = "0.3.0-alpha"
tokio = "0.2.0-alpha"
