[package]
name = "async-timer"
version = "0.2.3"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
description = "Timers for Rust async story"
readme = "README.md"
repository = "https://github.com/DoumanAsh/async-timer"
license = "Apache-2.0"
keywords = ["timer", "async", "wasm"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[features]
default = []
# Requires alloc
no_std = []
# Enables usage of romio
romio_on = ["mio", "romio", "nix"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
libc = "0.2"

[target.'cfg(any(target_os = "bitrig", target_os = "dragonfly", target_os = "freebsd", target_os = "ios", target_os = "macos", target_os = "netbsd", target_os = "openbsd"))'.dependencies]
libc = "0.2"
nix = { version = "0.13", optional = true }
mio = { version = "0.6", optional = true }
romio = { version = "0.3.0-alpha.5", optional = true }

[target.'cfg(any(target_os = "linux", target_os = "android"))'.dependencies]
libc = "0.2"
lazy_static = "1"
mio = { version = "0.6", optional = true }
romio = { version = "0.3.0-alpha.5", optional = true }

[target.'cfg(any(target_arch = "wasm32"))'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["threadpoolapiset"]

[dev-dependencies.futures-preview]
version = "0.3.0-alpha.14"

