[package]
name = "async-timer"
version = "0.1.0"
authors = ["Douman <douman@gmx.se>"]
edition = "2018"
description = "Timers for Rust async story"
readme = "README.md"
repository = "https://github.com/DoumanAsh/async-timer"
license = "Apache-2.0"
keywords = ["timer", "async", "wasm"]
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md"
]

[features]
default = []
# Requires alloc
no_std = []

[target.'cfg(any(target_arch = "wasm32"))'.dependencies]
wasm-bindgen = "0.2"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = ["threadpoolapiset"]

[dev-dependencies.futures-preview]
version = "0.3.0-alpha.14"

