name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Install Rust Unix
      if: runner.os != 'Windows'
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain stable
        echo ::add-path::$HOME/.cargo/bin
    - name: Install Rust Windows
      if: runner.os == 'Windows'
      run: |
        Invoke-WebRequest https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe -OutFile rustup-init.exe
        ./rustup-init.exe -y --profile minimal --default-toolchain stable
        echo ::add-path::%USERPROFILE%\.cargo\bin

    - name: Rust version
      run: |
        rustup update
        cargo --version
        rustc --version

    - name: Check no_std
      if: runner.os != 'Linux'
      run: cargo check --all --features no_std

    - name: Check WASM
      run: |
        rustup target add wasm32-unknown-unknown
        cargo check --target wasm32-unknown-unknown --features no_std

    - name: Test with tokio
      if: runner.os != 'Windows'
      run: cargo test --features tokio_on

    - name: Test
      run: cargo test --all --features stream
